-- ---------------------------------------------------------------------------
-- SITPa 2.0 - esquema inicial.
--
-- O DDL usa apenas construcoes do SQL padrao (IDENTITY, TIMESTAMP WITH TIME ZONE)
-- para que a MESMA migracao rode no PostgreSQL de producao e no H2 usado em
-- desenvolvimento e nos testes. Assim o esquema testado e o esquema entregue.
-- ---------------------------------------------------------------------------

CREATE TABLE classificacao (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                      VARCHAR(60)  NOT NULL,
    nome                        VARCHAR(120) NOT NULL,
    cor                         VARCHAR(7)   NOT NULL,
    prioridade                  INTEGER      NOT NULL,
    tempo_maximo_espera_minutos INTEGER      NOT NULL,
    local_atendimento           VARCHAR(160) NOT NULL,
    tipo_atendimento            VARCHAR(160) NOT NULL,
    ativo                       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em                   TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_classificacao_codigo     UNIQUE (codigo),
    -- A escala de gravidade nao admite empates: e ela que decide "a mais grave".
    CONSTRAINT uk_classificacao_prioridade UNIQUE (prioridade)
);

CREATE TABLE grupo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(60)  NOT NULL,
    nome          VARCHAR(120) NOT NULL,
    descricao     VARCHAR(500),
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_grupo_codigo UNIQUE (codigo)
);

CREATE TABLE fluxograma (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(60)  NOT NULL,
    nome          VARCHAR(120) NOT NULL,
    descricao     VARCHAR(500),
    grupo_id      BIGINT       NOT NULL,
    modelo_dmn    VARCHAR(120),
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fluxograma_codigo UNIQUE (codigo),
    CONSTRAINT fk_fluxograma_grupo  FOREIGN KEY (grupo_id) REFERENCES grupo (id)
);

CREATE TABLE sintoma (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(80)  NOT NULL,
    nome              VARCHAR(160) NOT NULL,
    descricao         VARCHAR(500),
    classificacao_id  BIGINT       NOT NULL,
    ativo             BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em         TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_sintoma_codigo         UNIQUE (codigo),
    CONSTRAINT fk_sintoma_classificacao  FOREIGN KEY (classificacao_id) REFERENCES classificacao (id)
);

-- Associacao N:N com atributo proprio: a gravidade de um discriminador pode mudar
-- conforme a queixa, entao a relacao carrega uma classificacao especifica opcional.
CREATE TABLE fluxograma_sintoma (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fluxograma_id               BIGINT  NOT NULL,
    sintoma_id                  BIGINT  NOT NULL,
    classificacao_especifica_id BIGINT,
    ordem                       INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_fluxograma_sintoma UNIQUE (fluxograma_id, sintoma_id),
    CONSTRAINT fk_fs_fluxograma      FOREIGN KEY (fluxograma_id) REFERENCES fluxograma (id),
    CONSTRAINT fk_fs_sintoma         FOREIGN KEY (sintoma_id) REFERENCES sintoma (id),
    CONSTRAINT fk_fs_classificacao   FOREIGN KEY (classificacao_especifica_id) REFERENCES classificacao (id)
);

CREATE TABLE usuario (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login      VARCHAR(80)  NOT NULL,
    nome       VARCHAR(160) NOT NULL,
    senha_hash VARCHAR(100) NOT NULL,
    perfil     VARCHAR(20)  NOT NULL,
    ativo      BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuario_login UNIQUE (login)
);

CREATE TABLE regra_protocolo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120) NOT NULL,
    descricao     VARCHAR(500),
    tipo          VARCHAR(10)  NOT NULL,
    conteudo      TEXT         NOT NULL,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    versao        BIGINT       NOT NULL DEFAULT 0,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_regra_nome UNIQUE (nome)
);

-- Historico. Guarda os textos por copia, e nao por chave estrangeira, para que
-- editar o protocolo hoje nao reescreva o que foi decidido no atendimento de ontem.
CREATE TABLE classificacao_realizada (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    realizada_em                TIMESTAMP WITH TIME ZONE NOT NULL,
    grupo_id                    BIGINT,
    fluxograma_id               BIGINT,
    classificacao_id            BIGINT,
    grupo_nome                  VARCHAR(120) NOT NULL,
    fluxograma_nome             VARCHAR(120) NOT NULL,
    classificacao_codigo        VARCHAR(60)  NOT NULL,
    classificacao_nome          VARCHAR(120) NOT NULL,
    classificacao_cor           VARCHAR(7)   NOT NULL,
    classificacao_prioridade    INTEGER      NOT NULL,
    tempo_maximo_espera_minutos INTEGER      NOT NULL,
    local_atendimento           VARCHAR(160) NOT NULL,
    tipo_atendimento            VARCHAR(160) NOT NULL,
    origem_decisao              VARCHAR(20)  NOT NULL,
    regra_aplicada              VARCHAR(200),
    justificativa               VARCHAR(1000),
    identificador_paciente      VARCHAR(80),
    idade_anos                  INTEGER,
    observacoes                 VARCHAR(1000),
    usuario_login               VARCHAR(80)  NOT NULL
);

CREATE TABLE classificacao_realizada_sintoma (
    classificacao_realizada_id BIGINT       NOT NULL,
    sintoma_nome               VARCHAR(160) NOT NULL,
    CONSTRAINT fk_crs_classificacao_realizada
        FOREIGN KEY (classificacao_realizada_id) REFERENCES classificacao_realizada (id)
);

CREATE INDEX ix_cr_realizada_em  ON classificacao_realizada (realizada_em);
CREATE INDEX ix_cr_classificacao ON classificacao_realizada (classificacao_id);
CREATE INDEX ix_cr_fluxograma    ON classificacao_realizada (fluxograma_id);
CREATE INDEX ix_cr_grupo         ON classificacao_realizada (grupo_id);
CREATE INDEX ix_crs_registro     ON classificacao_realizada_sintoma (classificacao_realizada_id);
